error handling
handleError: anError
	errors add: anError