testing
testWithErrorInSetup
	self assert: a equals: 41